import { test, expect } from "@playwright/test";

test.use({ actionTimeout: 10_000 });

test("build a human form and loop, validate input, repeat and finish with persisted answers", async ({ page, request }, testInfo) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  const node = (id, type, name, x, config = {}) => ({ id, type, name, position: { x, y: 160 }, config });
  const response = await request.post("/api/v1/processes", { data: { name: `Форма и цикл ${testInfo.project.name}`, graph: {
    nodes: [node("start", "start", "Старт", 0), node("review", "approval", "Проверка материала", 260), node("loop", "loop", "Повторить проверку", 520, { condition: { source: "last_output", operator: "contains", value: "Доработать", caseSensitive: false }, maxIterations: 3 }), node("end", "end", "Готово", 780)],
    edges: [{ id: "s-r", source: "start", target: "review", branch: "default" }, { id: "r-l", source: "review", target: "loop", branch: "default" }, { id: "l-r", source: "loop", target: "review", branch: "repeat" }, { id: "l-e", source: "loop", target: "end", branch: "exit" }],
  } } });
  expect(response.ok(), await response.text()).toBe(true);
  const process = await response.json();
  await page.goto(`/#processes?processId=${process.id}&nodeId=review`);
  await expect(page).toHaveTitle(/АГАТ|Agat/i);
  const inspector = page.locator(".process-inspector");
  await expect(inspector.getByRole("heading", { name: "Проверка материала", exact: true })).toBeVisible();
  await inspector.getByRole("combobox", { name: "Действие человека", exact: true }).selectOption("input");
  await inspector.getByLabel("Заголовок формы", { exact: true }).fill("Проверка и дополнение");
  await inspector.getByLabel("Название поля 1", { exact: true }).fill("Решение редактора");
  await inspector.getByLabel("Ключ поля 1", { exact: true }).fill("decision");
  await inspector.getByRole("combobox", { name: "Тип поля 1", exact: true }).selectOption("select");
  await inspector.getByRole("textbox", { name: "Варианты поля 1, по одному в строке", exact: true }).fill("Доработать\nГотово");
  await inspector.getByRole("button", { name: "Добавить поле", exact: true }).click();
  await inspector.getByLabel("Название поля 2", { exact: true }).fill("Комментарий редактора");
  await inspector.getByLabel("Ключ поля 2", { exact: true }).fill("notes");
  await inspector.getByRole("combobox", { name: "Тип поля 2", exact: true }).selectOption("textarea");
  await inspector.getByText("Предпросмотр формы", { exact: true }).click();
  await expect(inspector.getByLabel("Решение редактора")).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("form-builder.png"), fullPage: true });
  await inspector.getByRole("button", { name: "Закрыть настройки", exact: true }).click();
  // The canvas also exposes every step as a keyboard-accessible button.
  await page.getByRole("button", { name: "Цикл: Повторить проверку", exact: true }).click();
  await inspector.getByRole("combobox", { name: "Режим", exact: true }).selectOption("count");
  await expect(inspector.getByLabel("Число повторов", { exact: true })).toBeVisible();
  await inspector.getByRole("combobox", { name: "Режим", exact: true }).selectOption("condition");
  await inspector.getByRole("combobox", { name: "Проверять", exact: true }).selectOption("json");
  await inspector.getByLabel("Путь к полю").fill("form.decision");
  await inspector.getByRole("combobox", { name: "Условие", exact: true }).selectOption("equals");
  await inspector.getByLabel("Значение", { exact: true }).fill("Доработать");
  await inspector.getByLabel("Максимум повторов", { exact: true }).fill("2");
  await inspector.getByRole("combobox", { name: "Повторять с шага", exact: true }).selectOption("");
  await inspector.getByRole("combobox", { name: "После цикла перейти к", exact: true }).selectOption("");
  await inspector.getByRole("combobox", { name: "Повторять с шага", exact: true }).selectOption("review");
  await inspector.getByRole("combobox", { name: "После цикла перейти к", exact: true }).selectOption("end");
  await inspector.getByRole("combobox", { name: "После цикла перейти к", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("loop-editor.png"), fullPage: true });
  await inspector.getByRole("button", { name: "Закрыть настройки", exact: true }).click();
  await page.getByRole("button", { name: "Опубликовать", exact: true }).click();
  await expect.poll(async () => (await (await request.get(`/api/v1/processes/${process.id}`)).json()).publishedVersion).toBe(1);
  await page.reload();
  const persisted = await (await request.get(`/api/v1/processes/${process.id}`)).json();
  expect(persisted.draftGraph.nodes.find((item) => item.id === "review").config.approvalForm.fields[0].id).toBe("decision");
  expect(persisted.draftGraph.edges.filter((item) => item.source === "loop").map((item) => item.branch).sort()).toEqual(["exit", "repeat"]);
  const started = await request.post(`/api/v1/processes/${process.id}/start`, { data: { input: "Материал для проверки", version: 1, startMode: "now" } });
  expect(started.ok(), await started.text()).toBe(true);
  const instance = await started.json();
  await page.goto("/#approvals");
  await page.locator(".approval-queue__item").filter({ hasText: process.name }).click();
  const submit = page.getByRole("button", { name: "Передать данные и продолжить", exact: true });
  await expect(submit).toBeVisible();
  await submit.click();
  await expect(page.getByText("Заполните обязательное поле", { exact: true })).toBeVisible();
  await page.getByLabel("Решение редактора").selectOption("Доработать");
  await page.getByLabel("Комментарий редактора").fill("Добавить источники");
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("approval-form.png"), fullPage: true });
  await page.locator(".process-human-form").scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("form-viewport.png"), fullPage: false });
  await page.locator(".process-human-form").screenshot({ path: testInfo.outputPath("form-controls.png") });
  const firstApproval = (await (await request.get("/api/v1/overview")).json()).approvals.find((approval) => approval.runId === instance.runId);
  await submit.click();
  await expect.poll(async () => {
    const overview = await (await request.get("/api/v1/overview")).json();
    return overview.approvals.find((approval) => approval.runId === instance.runId)?.stageId;
  }).not.toBe(firstApproval.stageId);
  await expect(page.locator(".approval-resolution")).toBeVisible();
  if (testInfo.project.name === "mobile-chromium") await page.getByRole("button", { name: "Все согласования", exact: true }).click();
  await page.locator(".approval-queue__item--pending").filter({ hasText: process.name }).click();
  await expect(page.getByLabel("Решение редактора")).toHaveValue("");
  await page.reload();
  await expect(submit).toBeVisible();
  await page.getByLabel("Решение редактора").selectOption("Готово");
  await submit.click();
  await expect.poll(async () => (await (await request.get(`/api/v1/runs/${instance.runId}`)).json()).status).toBe("completed");
  const finished = await (await request.get(`/api/v1/runs/${instance.runId}`)).json();
  expect(finished.stages).toHaveLength(2);
  expect(JSON.parse(finished.stages[0].output).form).toEqual({ decision: "Доработать", notes: "Добавить источники" });
  expect(JSON.parse(finished.stages[1].output).form.decision).toBe("Готово");
  await expect(page.locator(".approval-resolution")).toBeVisible();
  await expect(page.getByLabel("Решение редактора")).toBeDisabled();
  await expect(page.getByLabel("Решение редактора")).toHaveValue("Готово");
  expect(errors).toEqual([]);
  await expect(page.locator("vite-error-overlay")).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
});
