apiVersion: v1
kind: Service
metadata:
  name: agat-coordinator
  labels:
    app.kubernetes.io/name: agat
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/part-of: agat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agat
    app.kubernetes.io/component: coordinator
  ports:
    - name: http
      port: 8787
      targetPort: http
      protocol: TCP
