apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agat
resources:
  - namespace.yaml
  - coordinator-configmap.yaml
  - worker-configmap.yaml
  - persistent-volume-claims.yaml
  - keycloak-realm-configmap.yaml
  - keycloak.yaml
  - coordinator-postgres.yaml
  - temporal.yaml
  - local-worker-launcher-rbac.yaml
  - coordinator-deployment.yaml
  - coordinator-service.yaml
  - gateway.yaml
  - search.yaml
  - worker-deployment.yaml
configMapGenerator:
  - name: agat-postgres-init
    files:
      - init-agat.sh=postgres-init.sh
generatorOptions:
  disableNameSuffixHash: true
