apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agat-data
  labels:
    app.kubernetes.io/name: agat
    app.kubernetes.io/component: coordinator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agat-worker-state
  labels:
    app.kubernetes.io/name: agat
    app.kubernetes.io/component: worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
